### ISSUE TITLE
item-tile-group: Item tiles horizontal alignment issue

### ISSUE THREAD

**Issue by ArtBlue** [eBay/evo-web#160]
### I verified there's no existing issue for this bug.

- [x] There are no existing issues

<kbd><img width="813" alt="Image" src="https://github.com/user-attachments/assets/ea8ea0f4-7772-4a92-97f5-43244e2eaab7" /></kbd>

### Current behavior

The horizontal alignment of the dedicated sections - primary, secondary, and tertiary (specifically price) - do not align across tiles when sections get more content.

### Expected behavior

The horizontal alignment of the dedicated sections - primary, secondary, and tertiary (specifically price) - should align across tiles.

### Package and version

19.6.0

### Device/OS/Browser info

All

### Steps to reproduce

```bash
1.Enter more information in the body section of any tile in an item tile group
```

### Relevant code block

```scss
.item-tile__body {
    display: grid;
    grid-area: body;
    grid-template-areas:
        "section-primary"
        "section-secondary"
        "section-tertiary";
    grid-template-rows: 25px 0.75fr 1fr;
}
```

### Additional context

Dev note: 

`grid-template-rows: 25px 0.75fr 1fr;` is the culprit here. The `fr` units of secondary stretch that portion too much when the body grows.

Some solution options:

* Create a dedicated "price" section as part of the fix.
* Fix the height of the secondary section - (**preferable**)
* JS solution to set heights (least desirable)
